[workspace]
members = [
    'utils',
    'examples/ch5_hello_triangle',
    'examples/ch6_shaders/test_shader_lang',
]

[workspace.package]
authors = ["Kuriko Moe"]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
bytemuck = "1.11.0"
gl = "0.14.0"
once_cell = "1.13.0"
glutin = { git = "https://github.com/rust-windowing/glutin" }
anyhow = "1.0.61"
thiserror = "1.0.32"

[workspace.dependencies.learnopengl-utils]
path = 'utils'

